#!/bin/bash
#----------------------
# Testing clamav-milter
#----------------------
set -e
DAEMON=clamav-milter

if pidof -x $DAEMON > /dev/null; then
    echo "OK"
else
    echo "ERROR: ${DAEMON} IS NOT RUNNING"
    exit 1
fi
